// Code generated by templ@v0.2.364 DO NOT EDIT.

package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	helpers "github.com/pmwals09/yobs/internal"
)

func AttachmentsSection(od helpers.OpptyDetails) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<section id=\"attachments-section\" class=\"mb-4\"><h2 class=\"text-[1.5em]\">")
		if err != nil {
			return err
		}
		var_2 := `Attachments`
		_, err = templBuffer.WriteString(var_2)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h2>")
		if err != nil {
			return err
		}
		if od.Documents != nil && len(od.Documents) > 0 {
			_, err = templBuffer.WriteString("<table class=\"table-auto border-collapse w-full mb-4\"><thead><tr><th class=\"border-b text-left\">")
			if err != nil {
				return err
			}
			var_3 := `Title`
			_, err = templBuffer.WriteString(var_3)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</th><th class=\"border-b text-left\">")
			if err != nil {
				return err
			}
			var_4 := `Type`
			_, err = templBuffer.WriteString(var_4)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</th><th class=\"border-b text-left\">")
			if err != nil {
				return err
			}
			var_5 := `File Name`
			_, err = templBuffer.WriteString(var_5)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</th></tr></thead><tbody>")
			if err != nil {
				return err
			}
			for _, doc := range od.Documents {
				_, err = templBuffer.WriteString("<tr class=\"hover:bg-sky-100\"><td class=\"border-b\">")
				if err != nil {
					return err
				}
				var var_6 string = doc.Title
				_, err = templBuffer.WriteString(templ.EscapeString(var_6))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</td><td class=\"border-b\">")
				if err != nil {
					return err
				}
				var var_7 string = string(doc.Type)
				_, err = templBuffer.WriteString(templ.EscapeString(var_7))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</td><td class=\"border-b\"><a href=\"{ doc.URL }\">")
				if err != nil {
					return err
				}
				var var_8 string = doc.FileName
				_, err = templBuffer.WriteString(templ.EscapeString(var_8))
				if err != nil {
					return err
				}
				_, err = templBuffer.WriteString("</a></td></tr>")
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString("</tbody></table>")
			if err != nil {
				return err
			}
		}
		_, err = templBuffer.WriteString("<form method=\"POST\" action=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(insertIDIntoString("/opportunities/{}/upload", od.Oppty.ID)))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\" hx-post=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(insertIDIntoString("/opportunities/{}/upload", od.Oppty.ID)))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\" hx-target=\"#attachments-section\" enctype=\"multipart/form-data\"><label for=\"attachment-name\">")
		if err != nil {
			return err
		}
		var_9 := `Attachment Name`
		_, err = templBuffer.WriteString(var_9)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</label><input type=\"text\" name=\"attachment-name\" value=\"\"><label for=\"attachment-type\">")
		if err != nil {
			return err
		}
		var_10 := `Attachment Type`
		_, err = templBuffer.WriteString(var_10)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</label><select type=\"text\" name=\"attachment-type\"><option value=\"Resume\">")
		if err != nil {
			return err
		}
		var_11 := `Resume`
		_, err = templBuffer.WriteString(var_11)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</option><option value=\"CoverLetter\">")
		if err != nil {
			return err
		}
		var_12 := `Cover Letter`
		_, err = templBuffer.WriteString(var_12)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</option><option value=\"Communication\">")
		if err != nil {
			return err
		}
		var_13 := `Communication`
		_, err = templBuffer.WriteString(var_13)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</option></select><label for=\"attachment-file\">")
		if err != nil {
			return err
		}
		var_14 := `PDF Attachment`
		_, err = templBuffer.WriteString(var_14)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</label><input type=\"file\" name=\"attachment-file\" accept=\".pdf\"><input type=\"submit\" name=\"attachment-submit\" value=\"Submit\"></form></section>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
