// Code generated by templ@v0.2.364 DO NOT EDIT.

package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	helpers "github.com/pmwals09/yobs/internal"
)

func OpportunityForm(f helpers.FormData) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<form method=\"POST\" action=\"/opportunities\" hx-post=\"/opportunities\" hx-target=\"#main-content\" id=\"opportunity-form\" class=\"w-1/2\"><section class=\"grid grid-cols-2 gap-y-2\"><label for=\"opportunity-name\">")
		if err != nil {
			return err
		}
		var_2 := `Company Name`
		_, err = templBuffer.WriteString(var_2)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</label><input type=\"text\" name=\"opportunity-name\" value=\"\"><label for=\"opportunity-role\">")
		if err != nil {
			return err
		}
		var_3 := `Role`
		_, err = templBuffer.WriteString(var_3)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</label><input type=\"text\" name=\"opportunity-role\" value=\"\"><label for=\"opportunity-url\">")
		if err != nil {
			return err
		}
		var_4 := `URL`
		_, err = templBuffer.WriteString(var_4)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</label><input type=\"url\" name=\"opportunity-url\" value=\"\"><label for=\"opportunity-description\">")
		if err != nil {
			return err
		}
		var_5 := `Description`
		_, err = templBuffer.WriteString(var_5)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</label><textarea rows=\"3\" name=\"opportunity-description\"></textarea><label for=\"opportunity-date\">")
		if err != nil {
			return err
		}
		var_6 := `Application Date (if applicable)`
		_, err = templBuffer.WriteString(var_6)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</label><input type=\"date\" name=\"opportunity-date\" value=\"\"></section><section class=\"my-8\"><input type=\"submit\" name=\"submit\" value=\"Submit\" class=\"bg-gray-400 px-4 py-2 rounded-full mx-auto block hover:cursor-pointer\"></section></form>")
		if err != nil {
			return err
		}
		err = UnsafeRawHtml(f.Errors["overall"]).Render(ctx, templBuffer)
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
