// Code generated by templ@v0.2.364 DO NOT EDIT.

package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	helpers "github.com/pmwals09/yobs/internal"
	"github.com/pmwals09/yobs/internal/models/user"
)

func OpportunityDetailsPage(user *user.User, od helpers.OpptyDetails) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var_2 := templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
			templBuffer, templIsBuffer := w.(*bytes.Buffer)
			if !templIsBuffer {
				templBuffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templBuffer)
			}
			_, err = templBuffer.WriteString("<h1 class=\"text-center text-[2em]\">")
			if err != nil {
				return err
			}
			var var_3 string = od.Oppty.CompanyName
			_, err = templBuffer.WriteString(templ.EscapeString(var_3))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(" ")
			if err != nil {
				return err
			}
			var_4 := `- `
			_, err = templBuffer.WriteString(var_4)
			if err != nil {
				return err
			}
			var var_5 string = od.Oppty.Role
			_, err = templBuffer.WriteString(templ.EscapeString(var_5))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h1> <section class=\"mb-4\"><dl class=\"grid grid-cols-[min-content_auto] gap-x-4\"><dt class=\"font-bold whitespace-nowrap\">")
			if err != nil {
				return err
			}
			var_6 := `Company Name:`
			_, err = templBuffer.WriteString(var_6)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</dt><dd>")
			if err != nil {
				return err
			}
			var var_7 string = od.Oppty.CompanyName
			_, err = templBuffer.WriteString(templ.EscapeString(var_7))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</dd><dt class=\"font-bold whitespace-nowrap\">")
			if err != nil {
				return err
			}
			var_8 := `Role:`
			_, err = templBuffer.WriteString(var_8)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</dt><dd>")
			if err != nil {
				return err
			}
			var var_9 string = od.Oppty.Role
			_, err = templBuffer.WriteString(templ.EscapeString(var_9))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</dd><dt class=\"font-bold whitespace-nowrap\">")
			if err != nil {
				return err
			}
			var_10 := `URL:`
			_, err = templBuffer.WriteString(var_10)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</dt><dd>")
			if err != nil {
				return err
			}
			var var_11 string = od.Oppty.URL
			_, err = templBuffer.WriteString(templ.EscapeString(var_11))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</dd><dt class=\"font-bold whitespace-nowrap\">")
			if err != nil {
				return err
			}
			var_12 := `Status:`
			_, err = templBuffer.WriteString(var_12)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</dt><dd>")
			if err != nil {
				return err
			}
			var var_13 string = string(od.Oppty.Status)
			_, err = templBuffer.WriteString(templ.EscapeString(var_13))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</dd><dt class=\"font-bold whitespace-nowrap\">")
			if err != nil {
				return err
			}
			var_14 := `Application Date:`
			_, err = templBuffer.WriteString(var_14)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</dt><dd>")
			if err != nil {
				return err
			}
			var var_15 string = formatApplicationDate(od.Oppty.ApplicationDate)
			_, err = templBuffer.WriteString(templ.EscapeString(var_15))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</dd></dl></section> <section class=\"mb-4\"><h2 class=\"text-[1.5em]\">")
			if err != nil {
				return err
			}
			var_16 := `Job Description`
			_, err = templBuffer.WriteString(var_16)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h2> ")
			if err != nil {
				return err
			}
			var var_17 string = od.Oppty.Description
			_, err = templBuffer.WriteString(templ.EscapeString(var_17))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</section> <section class=\"mb-4\"><h2 class=\"text-[1.5em]\">")
			if err != nil {
				return err
			}
			var_18 := `Tasks`
			_, err = templBuffer.WriteString(var_18)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h2></section> ")
			if err != nil {
				return err
			}
			err = AttachmentsSection(od).Render(ctx, templBuffer)
			if err != nil {
				return err
			}
			if !templIsBuffer {
				_, err = io.Copy(w, templBuffer)
			}
			return err
		})
		err = base(user).Render(templ.WithChildren(ctx, var_2), templBuffer)
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
